name: vivanta_health
description: Wrapper for HealthKit on iOS and Google Fit and Health Connect on Android. Based on Cachet.dk Health Plugin
version: 8.1.0-2
homepage: https://docs.vivanta.io

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  device_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: cachet.plugins.health
        pluginClass: HealthPlugin
      ios:
        pluginClass: HealthPlugin
